### PR TITLE
Add @kylef's things

### PR DESCRIPTION
**Pull request by kylef**

### CODE REVIEW

**Comment by Danappelxx** [comment]
I believe he wants them to be in alphabetical order :)

**Comment by kylef** [comment]
Fixed, thanks @Danappelxx

**Comment by donald-pinckney** [comment]
At the most recent 0.5.0 tag of Spectre, Package.swift isn't actually committed yet, so it doesn't build with SPM.

**Comment by donald-pinckney** [comment]
@kylef Looks like the Package.swift was added recently, sorry I didn't merge this sooner.

**Comment by kylef** [comment]
Oops, sorry for not updating the status here. Thanks for merging.

**Pull request merged**
