### PR TITLE
added PureSwift repos

### PR DESCRIPTION
**Pull request by colemancda**

### CODE REVIEW

**Comment by donald-pinckney** [comment]
Sorry, I don't want to be picky, but does SwiftFoundation add value above [swift-corelibs-foundation](https://github.com/apple/swift-corelibs-foundation)?

**Comment by colemancda** [comment]
I was just discussion that, if you want the full discussion, log into [Zewo's Slack](https://zewo-slackin.herokuapp.com). Anyhow, its not class based, its protocol oriented based (structs). It removes the C dependency that Apple's Foundation has with CoreFoundation. Also, if you look at the unit tests, UUID and dates are faster, as it the whole framework due to protocol oriented programming.

**Comment by donald-pinckney** [comment]
Its an interesting thing to talk about, and I'm glad you have had the conversation.  Sounds good to me, especially while swift-corelibs-foundation is still partially implemented.  I'm going to go ahead and merge this, even though I won't be able to test linux stuff until tonight, at the earliest. Thanks for the contributions!

**Comment by colemancda** [comment]
@donald-pinckney Thanks. You can see the framework running on Linux on [Travis CI](https://travis-ci.org/PureSwift/SwiftFoundationExample/builds/95220827).

**Pull request merged**
